version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: walletOS-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: financeapp
    networks:
      - walletOS-net

  backend:
    build: ./backend
    container_name: walletOS-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/financeapp
      - JWT_SECRET=your_production_jwt_secret_here
      - JWT_EXPIRE=7d
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - walletOS-net

  frontend:
    build: ./frontend
    container_name: walletOS-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - walletOS-net

volumes:
  mongo_data:

networks:
  walletOS-net:
    driver: bridge
